<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="<?php echo $config->application->baseUrl; ?>/public/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="<?php echo $config->application->baseUrl; ?>/public/img/favicon.png" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Material Dashboard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="<?php echo $config->application->baseUrl; ?>/public/css/bootstrap.min.css" rel="stylesheet" />

    <!--  Material Dashboard CSS    -->
    <link href="<?php echo $config->application->baseUrl; ?>/public/css/material-dashboard.css" rel="stylesheet"/>

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="<?php echo $config->application->baseUrl; ?>/public/css/demo.css" rel="stylesheet" />
    <!--link href="../../public/css/mdb.css" rel="stylesheet" type='text/css' /-->

    <!--     Fonts and icons     -->
    <link href="<?php echo $config->application->baseUrl; ?>/public/css/font-awesome.css" rel="stylesheet" />
</head>

<body>

	<div class="wrapper">

	    <div class="sidebar" data-color="purple" data-image="<?php echo $config->application->baseUrl; ?>/../public/img/sidebar-1.jpg">
			<!--
		        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

		        Tip 2: you can also add an image using data-image tag
		    -->


	    	<div class="sidebar-wrapper">
				<div class="logo" style="background-image:url('<?php echo $config->application->baseUrl; ?>/public/img/sidebar-5.jpg');padding-top:4em;padding-bottom:2em">
					<a href="#" style="font-family:Monotype Corsiva;font-size:48px;" class="simple-text">
						Ho<font style="color:#fff">sm</font>as
					</a>
					<p>Welcome, John Doe</p>
				</div>
	            <ul class="nav">
                        <li class="active">
                        <a>
	                        <i class="fa fa-user"></i>
                        <p>RECEPTIONIST</p>
                        </a>
                        </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Receptionist/Dashboard">
	                        <i class="fa fa-calendar"></i>
	                        <p>My Duty Roaster</p>
	                    </a>
	                </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Receptionist/viewPatients">
	                        <i class="fa fa-search"></i>
	                        <p>View Patient</p>
	                    </a>
	                </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Receptionist/addPatient">
	                        <i class="fa fa-plus"></i>
	                        <p>Register a new Patient</p>
	                    </a>
	                </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Receptionist/scheduleAppointments">
	                        <i class="fa fa-calendar"></i>
	                        <p>Check Appointments</p>
	                    </a>
	                </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Receptionist/manageRooms">
	                        <i class="fa fa-home"></i>
	                        <p>Manage Rooms</p>
	                    </a>
	                </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Receptionist/editProfile">
	                        <i class="fa fa-edit"></i>
	                        <p>Edit Profile</p>
	                    </a>
	                </li>
	            </ul>
	    	</div>
	    </div>

	    <div class="main-panel">
			<nav class="navbar navbar-transparent navbar-absolute">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="#"></a>
					</div>
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<li>
								<a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
	 							   <i class="fa fa-user"></i> <i class="fa fa-caret-down"></i>
	 							   <p class="hidden-lg hidden-md">Profile</p>
		 						</a>
								<ul class="dropdown-menu">
									<li><a href="<?php echo $config->application->baseUrl; ?>/modules/Laboratory/editProfile"><span class="fa fa-edit"></span> Edit Profile</a></li>
									<li><a href="<?php echo $config->application->baseUrl; ?>/logout" style="color:#e25050"><span class="fa fa-power-off"></span> Logout</a></li>
									<!--li><a href="#">You're now friend with Andrew</a></li>
									<li><a href="#">Another Notification</a></li>
									<li><a href="#">Another One</a></li-->
								</ul>
							</li>
						</ul>

						<form class="navbar-form navbar-right" role="search">
							<div class="form-group  is-empty">
								<input type="text" class="form-control" placeholder="Search">
								<span class="material-input"></span>
							</div>
							<button type="submit" class="btn btn-white btn-round btn-just-icon">
								<i class="fa fa-search"></i><div class="ripple-container"></div>
							</button>
						</form>
					</div>
				</div>
			</nav>
