    <link href="../../../public/css/site.min.css" rel="stylesheet" />
<?php include("auto_sider.phtml"); ?>
	        <div class="content">
	            <div class="container-fluid">
	                <div class="row">
	                    <div class="col-md-12">
	                        <div class="card">
	                            <div class="card-header" data-background-color="purple">
	                                <h4 class="title" align="center">View Patient</h4>									
	                            </div>
	                            <div class="card-content">
                                    <h4 align="center">Basic Details</h4>
									<div class="row">
										<div class="col-md-12">
										<label class="control-label" style="margin-right:1em;">Out Patient (Patient not admitted)</label>
										<?php if($status=="in"){ ?>
										<label class="toggle">
											<input type="checkbox" id="status" onchange="markPatient()" checked>
											<span class="handle" rel="tooltip" title="Present status of the Patient?"></span>
										</label>
										<?php }else if($status=="out"){ ?>
										<label class="toggle">
											<input type="checkbox" id="status" onchange="markPatient()">
											<span class="handle" rel="tooltip" title="Present status of the Patient?"></span>
										</label>
										<?php } ?>
										<label class="control-label" style="margin-left:1em;">In Patient (Patient Admitted)</label>
										</div>
									</div>
	                                    <div class="row">
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Surname</label>
                                                    <?php echo $surname; ?>
													<input type="hidden" value="<?php echo $id; ?>" id="id" />
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">First Name</label>
                                                    <?php echo $firstname; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Last Name</label>
                                                    <?php echo $lastname; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-12">
												<div class="form-group label-floating">
													<label class="control-label">Address</label>
                                                    <?php echo $address; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Age</label>
                                                    <?php echo $age; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Gender</label>
                                                    <?php echo $gender; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Occupation/Profession</label>
                                                    <?php echo $profession; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Email (optional)</label>
                                                    <?php echo $email; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Telephone</label>
                                                    <?php echo $fone; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Marital Status</label>
                                                    <?php echo $marital_status; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Next of Kin</label>
                                                    <?php echo $nok; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Next of Kin's Relationship</label>
                                                    <?php echo $nok_rel; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Next of Kin's Tel. Number</label>
                                                    <?php echo $nok_tel; ?>
												</div>
	                                        </div>
	                                    </div>
	                                    <div class="clearfix"></div>
	                                </form>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <footer class="footer">
	            <div class="container-fluid">
	                <nav class="pull-left">
	                    <ul>
	                        <li>
	                            <a href="#">
	                                Home
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Company
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Portfolio
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                               Blog
	                            </a>
	                        </li>
	                    </ul>
	                </nav>
	                <p class="copyright pull-right">
	                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
	                </p>
	            </div>
	        </footer>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="public/js/demo.js"></script>
	<script type="text/javascript">
	function markPatient(){
		if(document.getElementById('status').checked){
		var id = document.getElementById('id').value;
		$.ajax({
    		url: '<?php echo $config->application->baseUrl; ?>/modules/Receptionist/markPatient',
	        type: 'POST', 
	        data: 'status=in&patient='+id,
	        async: false,
	        success: function(s){
	        	freshevents = s;
	        }
		});
		console.log("Admitted");
		}
		else if(!document.getElementById('status').checked){
		console.log("Not Admitted"); 
		var id = document.getElementById('id').value;
		$.ajax({
    		url: '<?php echo $config->application->baseUrl; ?>/modules/Receptionist/markPatient',
	        type: 'POST', 
	        data: 'status=out&patient='+id,
	        async: false,
	        success: function(s){
	        	freshevents = s;
	        }
		});
		}
	}
	</script>
		<script src='<?php echo $config->application->baseUrl; ?>/public/js/jquery.min.js'></script>

</html>
