<?php include("auto_sider.phtml"); ?>
	        <div class="content">
	            <div class="container-fluid">
	                <div class="row">
	                    <div class="col-md-12">
	                        <div class="card">
	                            <div class="card-header" data-background-color="purple">
	                                <h4 class="title" align="center"><i class="fa fa-plus"></i> Register a new Room</h4>
	                            </div>
	                            <div class="card-content">
	                                <form method="POST" action="<?php echo $config->application->baseUrl; ?>/modules/Receptionist/createNewRoomController">
	                                    <div class="row">
	                                        <div class="col-md-12">
												<div class="form-group label-floating">
													<label class="control-label">Room Name</label>
													<input type="text" class="form-control" name="room_name">
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <!--div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Date of Payment</label>
													<input type="text" class="form-control" name="dop">
												</div>
	                                        </div-->
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Type</label>
													<select class="form-control" name="type">
                                                    <option value="General">General</option>
                                                    <option value="Intensive Care Unit">ICU</option>
                                                    <option value="Private">Private</option>
                                                    </select>
												</div>
	                                        </div>
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Number of Beds</label>
													<select class="form-control" name="nos">
                                                    <option value="1">1</option>
                                                    <option value="2">2</option>
                                                    <option value="3">3</option>
                                                    <option value="4">4</option>
                                                    <option value="5">5</option>
                                                    <option value="6">6</option>
                                                    <option value="7">7</option>
                                                    <option value="8">8</option>
                                                    <option value="9">9</option>
                                                    <option value="10">10</option>
                                                    </select>
												</div>
	                                        </div>
	                                    </div>

	                                    <button type="submit" class="btn btn-primary pull-right">Add Room</button>
	                                    <div class="clearfix"></div>
	                                </form>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <footer class="footer">
	            <div class="container-fluid">
	                <nav class="pull-left">
	                    <ul>
	                        <li>
	                            <a href="#">
	                                Home
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Company
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Portfolio
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                               Blog
	                            </a>
	                        </li>
	                    </ul>
	                </nav>
	                <p class="copyright pull-right">
	                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
	                </p>
	            </div>
	        </footer>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/demo.js"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/custom.min.js"></script>

	<script type="text/javascript">
    	$(document).ready(function(){

			// Javascript method's body can be found in public/js/demos.js
        	demo.initDashboardPageCharts();

    	});
	</script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-scroller/js/dataTables.scroller.min.js"></script>

</html>
