<?php include("auto_side.phtml"); ?>
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12 col-md-12">
							<div class="card card-nav-tabs">
								<div class="card-header" data-background-color="purple">
									<div class="nav-tabs-navigation">
										<div class="nav-tabs-wrapper" style="padding:0em;margin:0em;">
											<p align="center" style="font-size:20px;">
                                                <i class="fa fa-list"></i> 
                                                 MANAGE STAFFS
                                            </p>
										</div>
									</div>
								</div>

								<div class="card-content">
									<div class="tab-content">
										<div class="tab-pane active" id="profile">
											<p align="left" style="">
												<a href="addNewStaff">
													<button class="btn btn-primary">
														<i class="fa fa-plus"></i>
														 Add a Staff
													</button>
												 </a> 
											</p>
											<p align="right" style="">
													<!--form class="navbar-form navbar-right" role="search" action="searchStaffController" method="POST">
														<div class="form-group  is-empty">
															<input type="text" class="form-control" placeholder="Search">
															<span class="material-input"></span>
														</div>
														<button type="submit" class="btn btn-primary btn-round btn-just-icon">
															<i class="material-icons">search</i><div class="ripple-container"></div>
														</button>
													</form-->
													<br/>
                                            </p>
											<table class="table" id="datatable">
                                                <thead class="text-primary">
                                                    <th>ID</th>
                                                    <th>Name</th>
                                                    <th>Position</th>
													<th></th>
                                                </thead>
												<tbody>
					        <?php foreach ($staffs as $staff){ ?>
													<tr>
														<td>
                                                               1.
														</td>
														<td>
															<a style="color:#000" role="button" href="viewStaff/<?php echo $staff->id; ?>">
																	<?php echo $staff->firstname." ".$staff->othernames; ?> <br/>
															</a>
														</td>
														<td>
															<?php echo $staff->rank; ?>
														</td>
														<td class="td-actions text-right">
															<a href="editStaff/<?php echo $staff->id; ?>"> 
																<button type="button" rel="tooltip" title="Edit Staff" class="btn btn-primary btn-simple btn-xs">
																	<i class="fa fa-edit"></i>
																</button>
															</a>
																<button type="button" rel="tooltip" title="Remove Staff" class="btn btn-danger btn-simple btn-xs" onclick="alertGo('Are You Sure you want to Remove this staff?','deleteStaffController/<?php echo $staff->id; ?>')">
																	<i class="fa fa-trash-o"></i>
																</button>
														</td>
													</tr>
											<?php } ?>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>

			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul>
							<li>
								<a href="#">
									Home
								</a>
							</li>
							<li>
								<a href="#">
									Company
								</a>
							</li>
							<li>
								<a href="#">
									Portfolio
								</a>
							</li>
							<li>
								<a href="#">
								   Blog
								</a>
							</li>
						</ul>
					</nav>
					<p class="copyright pull-right">
						&copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
					</p>
				</div>
			</footer>
		</div>
	</div>

</body>
	<script type="text/javascript">
		function alertGo(text,location){
			var msg = text;
			var loc = location;
			alert(msg);
			if(confirm(msg)){
			window.location = loc;
			}
		}
	</script>
	<!--   Core JS Files   -->
	<script src="../../public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="../../public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="../../public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="../../public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="../../public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="../../public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="../../public/js/demo.js"></script>
	<script src="../../public/js/custom.min.js"></script>

	<script type="text/javascript">

    	$(document).ready(function(){

			// Javascript method's body can be found in public/js/demos.js
        	demo.initDashboardPageCharts();

    	});
	</script>
    <script src="../../public/js/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../../public/js/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="../../public/js/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../../public/js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="../../public/js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="../../public/js/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="../../public/js/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../../public/js/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="../../public/js/datatables.net-scroller/js/dataTables.scroller.min.js"></script>

</html>
