<?php include("auto_side.phtml"); ?>
	        <div class="content">
	            <div class="container-fluid">
	                <div class="row">
	                    <div class="col-md-12">
	                        <div class="card">
	                            <div class="card-header" data-background-color="purple">
	                                <h4 class="title" align="center">View Patient</h4>
	                            </div>
	                            <div class="card-content">
                                    <h4 align="center">Basic Details</h4>
	                                    <div class="row">
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Surname</label>
                                                    <?php echo $surname; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">First Name</label>
                                                    <?php echo $firstname; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Last Name</label>
                                                    <?php echo $lastname; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-12">
												<div class="form-group label-floating">
													<label class="control-label">Address</label>
                                                    <?php echo $address; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Age</label>
                                                    <?php echo $age; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Gender</label>
                                                    <?php echo $gender; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Occupation/Profession</label>
                                                    <?php echo $profession; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Email (optional)</label>
                                                    <?php echo $email; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Telephone</label>
                                                    <?php echo $fone; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Marital Status</label>
                                                    <?php echo $marital_status; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Next of Kin</label>
                                                    <?php echo $nok; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Next of Kin's Relationship</label>
                                                    <?php echo $nok_rel; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-4">
												<div class="form-group label-floating">
													<label class="control-label">Next of Kin's Tel. Number</label>
                                                    <?php echo $nok_tel; ?>
												</div>
	                                        </div>
	                                    </div>
                                        <h4 align="center">All Medical Records</h4>
                                        <h4 align="center">All Billing History</h4>
											<table class="table" id="datatable">
                                                <thead style="font-size:15px" class="text-primary">
												 <tr>
                                                    <th>S/N</th>
													<th>Price</th>
													<th>Payment For</th>
													<th>Date Paid</th>
													<th>Paid By</th>
													<th>Recieved by</th>
													<th>Status<th>
												 </tr>
												</thead>
												<tbody>
					        		<?php foreach ($bills as $bill){ ?>
													<tr>
														<td>
                                                                1.
														</td>
														<td>
															₦<?php echo $bill->price; ?>
														</td>
														<td>
															<?php echo $bill->bill_name; ?>
														</td>
														<td>
															<?php echo $bill->dop; ?>
														</td>
														<td>
															<?php echo $bill->payer; ?>
														</td>
														<td>
															<?php echo $bill->recieved_by; ?>
														</td>
														<td>
															<?php echo $bill->payment_status; ?>
														</td>
													</tr>
											<?php } ?>
												</tbody>
											</table>
	                                    <div class="clearfix"></div>
	                                </form>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <footer class="footer">
	            <div class="container-fluid">
	                <nav class="pull-left">
	                    <ul>
	                        <li>
	                            <a href="#">
	                                Home
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Company
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Portfolio
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                               Blog
	                            </a>
	                        </li>
	                    </ul>
	                </nav>
	                <p class="copyright pull-right">
	                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
	                </p>
	            </div>
	        </footer>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="<?php echo $config->application->baseUrl; ?>public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="<?php echo $config->application->baseUrl; ?>public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="<?php echo $config->application->baseUrl; ?>public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="<?php echo $config->application->baseUrl; ?>public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="<?php echo $config->application->baseUrl; ?>public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="<?php echo $config->application->baseUrl; ?>public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="<?php echo $config->application->baseUrl; ?>public/js/demo.js"></script>

</html>
