<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="../../public/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="../../public/img/favicon.png" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Material Dashboard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="<?php echo $config->application->baseUrl; ?>/public/css/bootstrap.min.css" rel="stylesheet" type='text/css'/>

    <!--  Material Dashboard CSS    -->
    <link href="<?php echo $config->application->baseUrl; ?>/public/css/material-dashboard.css" rel="stylesheet"type='text/css'/>
    <!--link href="../../public/css/mdb.css" rel="stylesheet" type='text/css' /-->

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="<?php echo $config->application->baseUrl; ?>/public/css/demo.css" rel="stylesheet" type='text/css'/>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>

    <!--     Fonts and icons     -->
    <link href="<?php echo $config->application->baseUrl; ?>/public/css/font-awesome.css" rel="stylesheet" type='text/css'/>
    <link href="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet" type='text/css'>
    <link href="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet" type='text/css'>
    <link href="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet" type='text/css'>
    <link href="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet" type='text/css'>
    <link href="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet" type='text/css'>
	<link href='<?php echo $config->application->baseUrl; ?>/public/css/fullcalendar.css' rel='stylesheet' />
	<link href='<?php echo $config->application->baseUrl; ?>/public/css/fullcalendar.print.css' rel='stylesheet' media='print' />
</head>

<body>

	<div class="wrapper">

	    <div class="sidebar" data-color="purple" data-image="<?php echo $config->application->baseUrl; ?>/public/img/sidebar-1.jpg">
			<!--
		        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

		        Tip 2: you can also add an image using data-image tag
		    -->


	    	<div class="sidebar-wrapper">
			<div class="logo" style="background-image:url('<?php echo $config->application->baseUrl; ?>/public/img/sidebar-5.jpg');padding-top:4em;padding-bottom:4em">
				<a href="#" style="font-family:Monotype Corsiva;font-size:48px;" class="simple-text">
					Ho<font style="color:#fff">sm</font>as
				</a>
				<p>Welcome, John Doe</p>
			</div>
	            <ul class="nav">
	                <!--li class="active">
	                    <a href="dashboard.html">
	                        <i class="material-icons">dashboard</i>
	                        <p>Dashboard</p>
	                    </a>
	                </li-->
                        <li class="active">
                        <a>
	                        <i class="fa fa-user"></i>
                        <p>LABORATORY</p>
                        </a>
                        </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Laboratory/Dashboard">
	                        <i class="fa fa-calendar"></i>
	                        <p>My Duty Schedule</p>
	                    </a>
	                </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Laboratory/createLabResult">
	                        <i class="fa fa-plus"></i>
	                        <p>Create Lab Test Result</p>
	                    </a>
	                </li>
	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Laboratory/checkPatientRecords">
	                        <i class="fa fa-search"></i>
	                        <p>View Laboratory Results</p>
	                    </a>
	                </li>

	                <li>
	                    <a href="<?php echo $config->application->baseUrl; ?>/modules/Laboratory/editProfile">
	                        <i class="fa fa-edit text-gray"></i>
	                        <p>Edit Profile</p>
	                    </a>
	                </li>
	            </ul>
	    	</div>
	    </div>

	    <div class="main-panel">
			<nav class="navbar navbar-transparent navbar-absolute">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<!--li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<i class="material-icons">notifications</i>
									<span class="notification">5</span>
									<p class="hidden-lg hidden-md">Notifications</p>
								</a>
								<ul class="dropdown-menu">
									<li><a href="#">Mike John responded to your email</a></li>
									<li><a href="#">You have 5 new tasks</a></li>
									<li><a href="#">You're now friend with Andrew</a></li>
									<li><a href="#">Another Notification</a></li>
									<li><a href="#">Another One</a></li>
								</ul>
							</li-->
							<li>
								<a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
	 							   <i class="fa fa-user"></i> <i class="fa fa-caret-down"></i>
	 							   <p class="hidden-lg hidden-md">Profile</p>
		 						</a>
								<ul class="dropdown-menu">
									<li><a href="<?php echo $config->application->baseUrl; ?>/modules/Laboratory/editProfile"><span class="fa fa-edit"></span> Edit Profile</a></li>
									<li><a href="<?php echo $config->application->baseUrl; ?>/logout" style="color:#e25050"><span class="fa fa-power-off"></span> Logout</a></li>
									<!--li><a href="#">You're now friend with Andrew</a></li>
									<li><a href="#">Another Notification</a></li>
									<li><a href="#">Another One</a></li-->
								</ul>
							</li>
						</ul>

						<form class="navbar-form navbar-right" role="search">
							<div class="form-group is-empty">
								<input type="text" class="form-control" placeholder="Search">
								<span class="material-input"></span>
							</div>
							<button type="submit" class="btn btn-white btn-round btn-just-icon">
								<i class="fa fa-search"></i><div class="ripple-container"></div>
							</button>
						</form>
					</div>
				</div>
			</nav>
