<?php include("auto_side.phtml"); ?>
	        <div class="content">
	            <div class="container-fluid">
	                <div class="row">
	                    <div class="col-md-12">
	                        <div class="card">
	                            <div class="card-header" data-background-color="purple">
	                                <h4 class="title" align="center"><i class="material-icons">add</i> Create a new Medical Bill</h4>
									<p class="category" align="center">For <font style="color:#fff"><?php echo $surname." ".$firstname." ".$lastname; ?></font> with Medical Record Number <font style="color:#fff"><?php echo $id; ?></font></p>
	                            </div>
	                            <div class="card-content">
	                                <form method="POST" action="<?php echo $config->application->baseUrl; ?>/modules/Accountant/createNewBillController">
	                                    <div class="row">
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Date</label>
													<input type="text" class="form-control" value="<?php echo date('d').'th of '.date('M').','.date('Y'); ?>" disabled>
													<input type="hidden" class="form-control" value="<?php echo date('d').'th of '.date('M').','.date('Y'); ?>" name="dop">
												</div>
	                                        </div>
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Reason for Billing / Billing Name</label>
													<input type="text" class="form-control" name="bill_name">
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Price (₦)</label>
													<input type="number" class="form-control" name="price">
													<input type="hidden" class="form-control" value="<?php echo $id; ?>" name="p_id">
													<input type="hidden" class="form-control" value="<?php echo $surname." ".$firstname." ".$lastname; ?>" name="patient_name">
													<input type="hidden" class="form-control" value="Jane Doe" name="recieved_by">
												</div>
	                                        </div>
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Payed By:</label>
													<input type="text" class="form-control" name="payed_by" required>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <!--div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Date of Payment</label>
													<input type="text" class="form-control" name="dop">
												</div>
	                                        </div-->
	                                        <div class="col-md-12">
												<div class="form-group label-floating">
													<label class="control-label">Payment Status</label>
													<select class="form-control" name="" disabled>
                                                    <option value="paid">Paid</option>
                                                    <option value="not paid">Not Paid</option>
                                                    </select>
													<input type="hidden" class="form-control" value="Paid" name="payment_status">
												</div>
	                                        </div>
	                                    </div>

	                                    <button type="submit" class="btn btn-primary pull-right">Add Bill</button>
	                                    <div class="clearfix"></div>
	                                </form>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <footer class="footer">
	            <div class="container-fluid">
	                <nav class="pull-left">
	                    <ul>
	                        <li>
	                            <a href="#">
	                                Home
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Company
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Portfolio
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                               Blog
	                            </a>
	                        </li>
	                    </ul>
	                </nav>
	                <p class="copyright pull-right">
	                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
	                </p>
	            </div>
	        </footer>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/demo.js"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/custom.min.js"></script>

	<script type="text/javascript">
    	$(document).ready(function(){

			// Javascript method's body can be found in public/js/demos.js
        	demo.initDashboardPageCharts();

    	});
	</script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-scroller/js/dataTables.scroller.min.js"></script>

</html>
