<?php include("auto_side.phtml"); ?>
	        <div class="content">
	            <div class="container-fluid">
	                <div class="row">
	                    <div class="col-md-12">
	                        <div class="card">
	                            <div class="card-header" data-background-color="purple">
	                                <h4 class="title" align="center">View Laboratory Result</h4>
									<p class="category" align="center">For <font style="color:#fff">John Doe</font> with Medical Record Number <font style="color:#fff">P-001</font></p>
	                            </div>
								<div class="card-content">
									<div class="tab-content">
										<div class="tab-pane active" id="profile">
											<table class="table" id="datatable">
                                                <thead style="font-size:15px" class="text-primary">
                                                    <th>S/N</th>
                                                    <th>Date</th>
													<th>Patient ID</th>
													<th>Name</th>
													<th></th>
                                                </thead>
												<tbody>
					        		<?php foreach ($patients as $patient){ ?>
													<tr>
														<td>
                                                                1.
														</td>
														<td>
														</td>
														<td>
														</td>
														<td>
																	<?php echo $patient->surname." ".$patient->firstname; ?> <br/>
															<br/>														
															<i><?php echo $patient->address; ?></i>
                                                        </td>
														<td class="td-actions text-right">
															<a href="checkPatientRecords/patient/<?php echo $patient->id; ?>"> 
																<button type="button" rel="tooltip" title="Search Patient" class="btn btn-primary btn-simple btn-xs">
																	<i class="material-icons">content_paste</i>
																</button>
															</a>
														</td>
													</tr>
											<?php } ?>
												</tbody>
											</table>
										</div>
									</div>
								</div>
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <footer class="footer">
	            <div class="container-fluid">
	                <nav class="pull-left">
	                    <ul>
	                        <li>
	                            <a href="#">
	                                Home
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Company
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Portfolio
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                               Blog
	                            </a>
	                        </li>
	                    </ul>
	                </nav>
	                <p class="copyright pull-right">
	                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
	                </p>
	            </div>
	        </footer>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="public/js/demo.js"></script>

</html>
