<?php include("auto_side.phtml"); ?>
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12 col-md-12">
							<div class="card card-nav-tabs">
								<br/>																		
								<div class="card-content">
									<div class="tab-content">
										<div class="tab-pane active" id="profile">
											<div class="col col-md-8"><h3 align=""><i class="fa fa-hospital-o" style="color:#e25050"></i> ABC Hospitals</h3>
											<p align=""><i>Address: No 2, ABC road, Time  qwerty, shshsjisis, djjdkkslld, dhjdjkdkkkd, Ilorin.</i></p></div>
											<div class="col col-md-3"><h5><b>Date:</b> 20th 0f Sept., 2017</h5><br/><br/><br/>
											</div>

											<h3 align="center" style=""><u>Payment Receipt</u></h3>

											<p align=""><b>Name:</b> Mr John M. Doe</p>
											<p align=""><b>Address:</b> jsjsjjs, sjjdkdks, sdjksksks, dkkdosmskd, sjsksaoooa, Ilorin, Kwara State.</p>
											<p align=""><b>Patient ID:</b> P-001</p>

											<table class="table" id="datatable">
												 <tr>
													<!--th>PID</th-->
                                                    <td>Payment For</th>
													<td>Price</td>
													<!--th>Date Paid</th>
													<th>Paid By</th>
													<th>Recieved by</th>
													<th>Status<th-->
												 </tr>
												<tr>
													<th>Sugar Test</th>
													<th>₦2,500</th>
												</tr>
												<tr>
													<th>Blood Test</th>
													<th>₦3,500</th>
												</tr>
												<tr>
													<th>Genotype Test</th>
													<th>₦1,500</th>
												</tr>
												<tr>
													<th>Total</th>
													<th>₦7,500</th>
												</tr>
											</table>											
											<br/>
											<p align="right"><b>Received by:</b> Mr John Doe</p>
											<p align="left"><button class="btn btn-primary" onclick="window.print()"><span class="fa fa-print"></span> Print</button></p>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>

			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul>
							<li>
								<a href="#">
									Home
								</a>
							</li>
							<li>
								<a href="#">
									Company
								</a>
							</li>
							<li>
								<a href="#">
									Portfolio
								</a>
							</li>
							<li>
								<a href="#">
								   Blog
								</a>
							</li>
						</ul>
					</nav>
					<p class="copyright pull-right">
						&copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
					</p>
				</div>
			</footer>
		</div>
	</div>

</body>
	<script type="text/javascript">
		function alertGo(text,location){
			var msg = text;
			var loc = location;
			alert(msg);
			window.location = loc;
		}
	</script>

	<!--   Core JS Files   -->
	<script src="../../public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="../../public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="../../public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="../../public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="../../public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="../../public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="../../public/js/demo.js"></script>
	<script src="../../public/js/custom.min.js"></script>

	<script type="text/javascript">
    	$(document).ready(function(){

			// Javascript method's body can be found in public/js/demos.js
        	demo.initDashboardPageCharts();

    	});
	</script>
    <script src="../../public/js/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../../public/js/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="../../public/js/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../../public/js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="../../public/js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="../../public/js/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="../../public/js/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../../public/js/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="../../public/js/datatables.net-scroller/js/dataTables.scroller.min.js"></script>

</html>
