<?php include("auto_side.phtml"); ?>
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12 col-md-12">
							<div class="card card-nav-tabs">
								<div class="card-header" data-background-color="purple">
									<div class="nav-tabs-navigation">
										<div class="nav-tabs-wrapper" style="">
											<h4 align="center" style=""><i class="fa fa-list"></i> ALL MEDICAL BILLS</h4>
										</div>
									</div>
								</div>
								<br/>
								
								<div class="card-content">
									<div class="tab-content">
										<div class="tab-pane active" id="profile">
											<table class="table" id="datatable">
                                                <thead style="font-size:15px" class="text-primary">
                                                    <th>S/N</th>
													<th>PID</th>
                                                    <th>Name</th>
													<th>Price</th>
													<th>Payment For</th>
													<th>Date Paid</th>
													<th>Paid By</th>
													<th>Recieved by</th>
													<th>Status<th>
                                                </thead>
												<tbody>
					        		<?php foreach ($bills as $bill){ ?>
													<tr>
														<td>
                                                                1.
														</td>
														<td>
															<?php echo $bill->p_id; ?>
														</td>
														<td>
															<?php echo $bill->patient_name; ?>
                                                        </td>
														<td>
															₦<?php echo $bill->price; ?>
														</td>
														<td>
															<?php echo $bill->bill_name; ?>
														</td>
														<td>
															<?php echo $bill->dop; ?>
														</td>
														<td>
															<?php echo $bill->payer; ?>
														</td>
														<td>
															<?php echo $bill->recieved_by; ?>
														</td>
														<td>
															<?php echo $bill->payment_status; ?>
														</td>
													</tr>
											<?php } ?>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>

			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul>
							<li>
								<a href="#">
									Home
								</a>
							</li>
							<li>
								<a href="#">
									Company
								</a>
							</li>
							<li>
								<a href="#">
									Portfolio
								</a>
							</li>
							<li>
								<a href="#">
								   Blog
								</a>
							</li>
						</ul>
					</nav>
					<p class="copyright pull-right">
						&copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
					</p>
				</div>
			</footer>
		</div>
	</div>

</body>
	<script type="text/javascript">
		function alertGo(text,location){
			var msg = text;
			var loc = location;
			alert(msg);
			window.location = loc;
		}
	</script>

	<!--   Core JS Files   -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/demo.js"></script>
	<script src="<?php echo $config->application->baseUrl; ?>/public/js/custom.min.js"></script>

	<script type="text/javascript">
    	$(document).ready(function(){

			// Javascript method's body can be found in public/js/demos.js
        	demo.initDashboardPageCharts();

    	});
	</script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="<?php echo $config->application->baseUrl; ?>/public/js/datatables.net-scroller/js/dataTables.scroller.min.js"></script>

</html>
