<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="public/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="public/img/favicon.png" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Material Dashboard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="public/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!--  Material Dashboard CSS    -->
    <link href="public/css/material-dashboard.css" rel="stylesheet" type="text/css" />

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="public/css/demo.css" rel="stylesheet" type="text/css" />

    <!--     Fonts and icons     -->
    <link href="public/css/font-awesome.css" rel="stylesheet" type="text/css">
    <!--link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'-->
</head>

<body>

	<div class="wrappers" style="background-color:#fff">
	    <div style="background-color:#fff" class="sidebars" data-color="white" data-image="public/img/sidebar-1.jpg">
						<br/><a class="navbar-brand" style="font-family:Monotype Corsiva;font-size:38px;background-color:#fff" href="#">Hosmas</a>
	    </div>

	    <div class="main-panel">
			<nav style="background-color:#fff" class="navbar navbar-transparent navbar-absolute">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" style="font-family:Monotype Corsiva;font-size:38px" href="#"></a>
					</div>
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<li>
								<a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
									<i class="fa fa-table"></i>
									<p class="hidden-lg hidden-md">Dashboard</p>
								</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<i class="fa fa-alert"></i>
									<span class="notification">5</span>
									<p class="hidden-lg hidden-md">Notifications</p>
								</a>
								<ul class="dropdown-menu">
									<li><a href="#">Mike John responded to your email</a></li>
									<li><a href="#">You have 5 new tasks</a></li>
									<li><a href="#">You're now friend with Andrew</a></li>
									<li><a href="#">Another Notification</a></li>
									<li><a href="#">Another One</a></li>
								</ul>
							</li>
							<li>
								<a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
	 							   <i class="fa fa-user"></i>
	 							   <p class="hidden-lg hidden-md">Profile</p>
	 						   </a>
							</li>
						</ul>

						<form class="navbar-form navbar-right" role="search">
							<div class="form-group  is-empty">
	                        	<input type="text" class="form-control" placeholder="Search">
	                        	<span class="material-input"></span>
							</div>
							<button type="submit" class="btn btn-white btn-round btn-just-icon">
								<span class="fa fa-search"></span><div class="ripple-container"></div>
							</button>
	                    </form>
					</div>
				</div>
			</nav>

	        <div class="content">
	            <div class="container-fluid">
	                <div class="row">
	                    <div class="col-md-2">
	                    </div>
						<div class="col-md-6">
    						<div class="card card-profile">
    							<div class="card-avatar">
    								<a href="#pablo">
    									<img class="img" src="public/img/faces/female_doctor2.png" />
    								</a>
    							</div>

    							<div class="card-content">
									<?php if(isset($_GET['err_msg'])){ ?>
									<div class="alert alert-danger">
	                                    <button type="button" aria-hidden="true" class="close">×</button>
	                                    <span style="font-size:16px"><b></b> <?php echo $_GET["err_msg"]; ?></span>
									</div>
									<?php } ?>
	                                <form action="AuthentificationController" method="POST">
	                                    <div class="row">
	                                        <div class="col-md-12">
	                                            <div class="form-group">
													<div class="form-group label-floating">
													<input type="text" class="form-control" style="font-size:24px" placeholder="Staff ID" name="staff_id" />
		                        					</div>
	                                            </div>
	                                        </div>
										</div>
										<div class="row">
	                                        <div class="col-md-12">
	                                            <div class="form-group">
													<div class="form-group label-floating">
													<input type="password" class="form-control" placeholder="Password"  style="font-size:24px" name="password" />
		                        					</div>
	                                            </div>
	                                        </div>
										</div>

										<div class="row">
	                                        <div class="col-md-12">
	                                    <button type="submit" class="btn btn-primary" style="width:470px">Login</button>
	                                    <div class="clearfix"></div>
	                                        </div>
										</div>
									</form>
    							</div>
    						</div>
		    			</div>
	                </div>
	            </div>
	        </div>

	        <footer class="footer">
	            <div class="container-fluid">
	                <nav class="pull-left">
	                    <ul>
	                        <li>
	                            <a href="#">
	                                Home
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Company
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Portfolio
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                               Blog
	                            </a>
	                        </li>
	                    </ul>
	                </nav>
	                <p class="copyright pull-right">
	                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
	                </p>
	            </div>
	        </footer>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="public/js/demo.js"></script>

</html>
