<?php include("auto_sider.phtml"); ?>
  
       
	        <div class="content">
	            <div class="container-fluid">
	                <div class="row">
	                    <div class="col-md-12">
	                        <div class="card">
	                            <div class="card-header" data-background-color="purple">
	                                <h4 class="title"><i class="material-icons">person</i> View Profile</h4>
	                            </div>
	                            <div class="card-content">
									<?php if(isset($_GET['msg'])){ ?>
									<div class="alert alert-success">
	                                    <button type="button" aria-hidden="true" class="close">×</button>
	                                    <span style="font-size:16px"><b></b> <?php echo $_GET["msg"]; ?></span>
									</div>
									<?php } ?>

	                                <form action="../editStaffController" method="POST">
	                                    <div class="row">
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Fist Name</label>
													<?php echo $firstname; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Other Names</label>
													<?php echo $othernames; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Staff ID</label>
													<?php echo $staff_id; ?>
												</div>
	                                        </div>
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Position</label>
													<?php echo $rank; ?>
												</div>
	                                        </div>
	                                    </div>

	                                    <div class="row">
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Phone Number</label>
													<?php echo $fone; ?> 
												</div>
	                                        </div>
	                                        <div class="col-md-6">
												<div class="form-group label-floating">
													<label class="control-label">Email Address(optional)</label>
													<?php echo $email; ?>
												</div>
	                                        </div>
	                                    </div>
	                                    <div class="clearfix"></div>
	                                </form>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <footer class="footer">
	            <div class="container-fluid">
	                <nav class="pull-left">
	                    <ul>
	                        <li>
	                            <a href="#">
	                                Home
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Company
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                                Portfolio
	                            </a>
	                        </li>
	                        <li>
	                            <a href="#">
	                               Blog
	                            </a>
	                        </li>
	                    </ul>
	                </nav>
	                <p class="copyright pull-right">
	                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
	                </p>
	            </div>
	        </footer>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="../../../public/js/jquery-3.1.0.min.js" type="text/javascript"></script>
	<script src="../../../public/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="../../../public/js/material.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="../../../public/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="../../../public/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Material Dashboard javascript methods -->
	<script src="../../../public/js/material-dashboard.js"></script>

	<!-- Material Dashboard DEMO methods, don't include it in your project! -->
	<script src="../../../public/js/demo.js"></script>

</html>
